export default [
  {
    "no": 1,
    "itemId": "INT01",
    "section": "Interest (RIASEC)",
    "questionText": "Using tools to build or fix things.",
    "facetCode": "R",
    "facetName": "Realistic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 2,
    "itemId": "INT02",
    "section": "Interest (RIASEC)",
    "questionText": "Doing activities that involve working with my hands.",
    "facetCode": "R",
    "facetName": "Realistic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 3,
    "itemId": "INT03",
    "section": "Interest (RIASEC)",
    "questionText": "Spending time outside, like gardening or exploring nature.",
    "facetCode": "R",
    "facetName": "Realistic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 4,
    "itemId": "INT04",
    "section": "Interest (RIASEC)",
    "questionText": "Doing physical tasks like lifting or carrying things.",
    "facetCode": "R",
    "facetName": "Realistic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 5,
    "itemId": "INT05",
    "section": "Interest (RIASEC)",
    "questionText": "Learning how things like machines or gadgets work.",
    "facetCode": "R",
    "facetName": "Realistic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 6,
    "itemId": "INT06",
    "section": "Interest (RIASEC)",
    "questionText": "Solving puzzles or tricky problems.",
    "facetCode": "I",
    "facetName": "Investigative",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 7,
    "itemId": "INT07",
    "section": "Interest (RIASEC)",
    "questionText": "Doing science experiments to learn new things.",
    "facetCode": "I",
    "facetName": "Investigative",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 8,
    "itemId": "INT08",
    "section": "Interest (RIASEC)",
    "questionText": "Reading books or articles about science.",
    "facetCode": "I",
    "facetName": "Investigative",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 9,
    "itemId": "INT09",
    "section": "Interest (RIASEC)",
    "questionText": "Finding patterns or solutions by looking at data.",
    "facetCode": "I",
    "facetName": "Investigative",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 10,
    "itemId": "INT10",
    "section": "Interest (RIASEC)",
    "questionText": "Exploring topics that interest me.",
    "facetCode": "I",
    "facetName": "Investigative",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 11,
    "itemId": "INT11",
    "section": "Interest (RIASEC)",
    "questionText": "Drawing, painting, or making crafts.",
    "facetCode": "A",
    "facetName": "Artistic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 12,
    "itemId": "INT12",
    "section": "Interest (RIASEC)",
    "questionText": "Writing stories, poems, or songs.",
    "facetCode": "A",
    "facetName": "Artistic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 13,
    "itemId": "INT13",
    "section": "Interest (RIASEC)",
    "questionText": "Playing music or singing.",
    "facetCode": "A",
    "facetName": "Artistic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 14,
    "itemId": "INT14",
    "section": "Interest (RIASEC)",
    "questionText": "Dancing to express myself.",
    "facetCode": "A",
    "facetName": "Artistic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 15,
    "itemId": "INT15",
    "section": "Interest (RIASEC)",
    "questionText": "Creating my own art projects.",
    "facetCode": "A",
    "facetName": "Artistic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 16,
    "itemId": "INT16",
    "section": "Interest (RIASEC)",
    "questionText": "Helping my friends with their problems.",
    "facetCode": "S",
    "facetName": "Social",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 17,
    "itemId": "INT17",
    "section": "Interest (RIASEC)",
    "questionText": "Working together with others on group projects.",
    "facetCode": "S",
    "facetName": "Social",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 18,
    "itemId": "INT18",
    "section": "Interest (RIASEC)",
    "questionText": "Teaching or explaining things to others.",
    "facetCode": "S",
    "facetName": "Social",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 19,
    "itemId": "INT19",
    "section": "Interest (RIASEC)",
    "questionText": "Volunteering or doing activities that help others.",
    "facetCode": "S",
    "facetName": "Social",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 20,
    "itemId": "INT20",
    "section": "Interest (RIASEC)",
    "questionText": "Leading a group.",
    "facetCode": "S",
    "facetName": "Social",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 21,
    "itemId": "INT21",
    "section": "Interest (RIASEC)",
    "questionText": "Taking the lead in organizing activities.",
    "facetCode": "E",
    "facetName": "Enterprising",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 22,
    "itemId": "INT22",
    "section": "Interest (RIASEC)",
    "questionText": "Convincing others to agree with my ideas.",
    "facetCode": "E",
    "facetName": "Enterprising",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 23,
    "itemId": "INT23",
    "section": "Interest (RIASEC)",
    "questionText": "Planning and making decisions for a team.",
    "facetCode": "E",
    "facetName": "Enterprising",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 24,
    "itemId": "INT24",
    "section": "Interest (RIASEC)",
    "questionText": "Taking on challenges to reach my goals.",
    "facetCode": "E",
    "facetName": "Enterprising",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 25,
    "itemId": "INT25",
    "section": "Interest (RIASEC)",
    "questionText": "Starting new projects or activities.",
    "facetCode": "E",
    "facetName": "Enterprising",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 26,
    "itemId": "INT26",
    "section": "Interest (RIASEC)",
    "questionText": "Organizing things neatly.",
    "facetCode": "C",
    "facetName": "Conventional",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 27,
    "itemId": "INT27",
    "section": "Interest (RIASEC)",
    "questionText": "Maintaining records and keeping track of tasks.",
    "facetCode": "C",
    "facetName": "Conventional",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 28,
    "itemId": "INT28",
    "section": "Interest (RIASEC)",
    "questionText": "Working with numbers or simple financial planning.",
    "facetCode": "C",
    "facetName": "Conventional",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 29,
    "itemId": "INT29",
    "section": "Interest (RIASEC)",
    "questionText": "Keeping notes of activities.",
    "facetCode": "C",
    "facetName": "Conventional",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 30,
    "itemId": "INT30",
    "section": "Interest (RIASEC)",
    "questionText": "Doing tasks that require careful attention.",
    "facetCode": "C",
    "facetName": "Conventional",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 31,
    "itemId": "PER01",
    "section": "Personality (OCEAN)",
    "questionText": "I enjoy exploring new ideas and learning about different subjects",
    "facetCode": "O",
    "facetName": "Openness",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 32,
    "itemId": "PER02",
    "section": "Personality (OCEAN)",
    "questionText": "I like trying out new activities that are different from what I usually do",
    "facetCode": "O",
    "facetName": "Openness",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 33,
    "itemId": "PER03",
    "section": "Personality (OCEAN)",
    "questionText": "I avoid doing things that are unfamiliar or new to me",
    "facetCode": "O",
    "facetName": "Openness",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 34,
    "itemId": "PER04",
    "section": "Personality (OCEAN)",
    "questionText": "I am curious and often wonder about how things work",
    "facetCode": "O",
    "facetName": "Openness",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 35,
    "itemId": "PER05",
    "section": "Personality (OCEAN)",
    "questionText": "I don't like changing my routine or trying new experiences",
    "facetCode": "O",
    "facetName": "Openness",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 36,
    "itemId": "PER06",
    "section": "Personality (OCEAN)",
    "questionText": "I struggle to engage with topics outside my knowledge",
    "facetCode": "O",
    "facetName": "Openness",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 37,
    "itemId": "PER07",
    "section": "Personality (OCEAN)",
    "questionText": "I always complete my tasks or homework on time",
    "facetCode": "Cn",
    "facetName": "Conscientiousness",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 38,
    "itemId": "PER08",
    "section": "Personality (OCEAN)",
    "questionText": "I like to stay organized and keep my things in order",
    "facetCode": "Cn",
    "facetName": "Conscientiousness",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 39,
    "itemId": "PER09",
    "section": "Personality (OCEAN)",
    "questionText": "I give my best in everything I do",
    "facetCode": "Cn",
    "facetName": "Conscientiousness",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 40,
    "itemId": "PER10",
    "section": "Personality (OCEAN)",
    "questionText": "I often leave tasks unfinished or forget to do them",
    "facetCode": "Cn",
    "facetName": "Conscientiousness",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 41,
    "itemId": "PER11",
    "section": "Personality (OCEAN)",
    "questionText": "I find it difficult to keep my things clean or organized",
    "facetCode": "Cn",
    "facetName": "Conscientiousness",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 42,
    "itemId": "PER12",
    "section": "Personality (OCEAN)",
    "questionText": "I don't always put much effort into my work or responsibilities",
    "facetCode": "Cn",
    "facetName": "Conscientiousness",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 43,
    "itemId": "PER13",
    "section": "Personality (OCEAN)",
    "questionText": "I enjoy being around others and making new friends",
    "facetCode": "Ex",
    "facetName": "Extraversion",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 44,
    "itemId": "PER14",
    "section": "Personality (OCEAN)",
    "questionText": "I feel excited and energized when I'm in a group or social setting",
    "facetCode": "Ex",
    "facetName": "Extraversion",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 45,
    "itemId": "PER15",
    "section": "Personality (OCEAN)",
    "questionText": "I like sharing my thoughts with people",
    "facetCode": "Ex",
    "facetName": "Extraversion",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 46,
    "itemId": "PER16",
    "section": "Personality (OCEAN)",
    "questionText": "I prefer to be alone rather than with people",
    "facetCode": "Ex",
    "facetName": "Extraversion",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 47,
    "itemId": "PER17",
    "section": "Personality (OCEAN)",
    "questionText": "I feel uncomfortable speaking in public",
    "facetCode": "Ex",
    "facetName": "Extraversion",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 48,
    "itemId": "PER18",
    "section": "Personality (OCEAN)",
    "questionText": "I find it tiring to be around others for too long",
    "facetCode": "Ex",
    "facetName": "Extraversion",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 49,
    "itemId": "PER19",
    "section": "Personality (OCEAN)",
    "questionText": "I am kind and helpful to others",
    "facetCode": "Ag",
    "facetName": "Agreeableness",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 50,
    "itemId": "PER20",
    "section": "Personality (OCEAN)",
    "questionText": "I enjoy working together with others to solve problems",
    "facetCode": "Ag",
    "facetName": "Agreeableness",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 51,
    "itemId": "PER21",
    "section": "Personality (OCEAN)",
    "questionText": "I try to get along with everyone and avoid arguments",
    "facetCode": "Ag",
    "facetName": "Agreeableness",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 52,
    "itemId": "PER22",
    "section": "Personality (OCEAN)",
    "questionText": "I find it hard to care about other people's feelings",
    "facetCode": "Ag",
    "facetName": "Agreeableness",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 53,
    "itemId": "PER23",
    "section": "Personality (OCEAN)",
    "questionText": "I often argue and don't mind disagreements with others",
    "facetCode": "Ag",
    "facetName": "Agreeableness",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 54,
    "itemId": "PER24",
    "section": "Personality (OCEAN)",
    "questionText": "I prefer to do things my way",
    "facetCode": "Ag",
    "facetName": "Agreeableness",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 55,
    "itemId": "PER25",
    "section": "Personality (OCEAN)",
    "questionText": "I stay calm and relaxed, even when things go wrong",
    "facetCode": "ES",
    "facetName": "Emotional Stability",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 56,
    "itemId": "PER26",
    "section": "Personality (OCEAN)",
    "questionText": "I can handle stress without getting too upset",
    "facetCode": "ES",
    "facetName": "Emotional Stability",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 57,
    "itemId": "PER27",
    "section": "Personality (OCEAN)",
    "questionText": "I feel confident and secure in myself most of the time",
    "facetCode": "ES",
    "facetName": "Emotional Stability",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 58,
    "itemId": "PER28",
    "section": "Personality (OCEAN)",
    "questionText": "I often feel restless or worried about things",
    "facetCode": "ES",
    "facetName": "Emotional Stability",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 59,
    "itemId": "PER29",
    "section": "Personality (OCEAN)",
    "questionText": "I get upset easily when things don't go as planned",
    "facetCode": "ES",
    "facetName": "Emotional Stability",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 60,
    "itemId": "PER30",
    "section": "Personality (OCEAN)",
    "questionText": "I struggle to stay calm under pressure",
    "facetCode": "ES",
    "facetName": "Emotional Stability",
    "responseType": "likert5",
    "reverseKeyed": "Yes",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 61,
    "itemId": "LRN01",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I understand lessons better when I see diagrams or pictures",
    "facetCode": "V",
    "facetName": "Visual",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 62,
    "itemId": "LRN02",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I prefer analysing charts or graphs instead of listening to explanations",
    "facetCode": "V",
    "facetName": "Visual",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 63,
    "itemId": "LRN03",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "When studying, I like using different colours to highlight important points",
    "facetCode": "V",
    "facetName": "Visual",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 64,
    "itemId": "LRN04",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I remember information better when it is presented in a flowchart or map",
    "facetCode": "V",
    "facetName": "Visual",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 65,
    "itemId": "LRN05",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I find it easier to follow instructions when they are shown as pictures",
    "facetCode": "V",
    "facetName": "Visual",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 66,
    "itemId": "LRN06",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I learn quickly when someone explains things to me verbally",
    "facetCode": "A",
    "facetName": "Auditory",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 67,
    "itemId": "LRN07",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I learn better when I discuss things with others",
    "facetCode": "A",
    "facetName": "Auditory",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 68,
    "itemId": "LRN08",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "Listening to recordings or podcasts helps me remember information",
    "facetCode": "A",
    "facetName": "Auditory",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 69,
    "itemId": "LRN09",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I enjoy listening to lectures more than reading textbooks",
    "facetCode": "A",
    "facetName": "Auditory",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 70,
    "itemId": "LRN10",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "Step-by-step instructions given verbally help me understand better",
    "facetCode": "A",
    "facetName": "Auditory",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 71,
    "itemId": "LRN11",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I prefer taking notes and reading them to learn new things",
    "facetCode": "Rd",
    "facetName": "Reading/Writing",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 72,
    "itemId": "LRN12",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I enjoy reading stories, articles, or essays to explore new ideas",
    "facetCode": "Rd",
    "facetName": "Reading/Writing",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 73,
    "itemId": "LRN13",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "Reading textbooks or articles helps me understand information quickly",
    "facetCode": "Rd",
    "facetName": "Reading/Writing",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 74,
    "itemId": "LRN14",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I like organizing my thoughts by writing them in a journal or notebook",
    "facetCode": "Rd",
    "facetName": "Reading/Writing",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 75,
    "itemId": "LRN15",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I find it easier to learn when I read instructions carefully",
    "facetCode": "Rd",
    "facetName": "Reading/Writing",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 76,
    "itemId": "LRN16",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I understand concepts better when I do practical activities",
    "facetCode": "K",
    "facetName": "Kinesthetic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 77,
    "itemId": "LRN17",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I prefer learning by trying things out rather than just reading about them",
    "facetCode": "K",
    "facetName": "Kinesthetic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 78,
    "itemId": "LRN18",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I remember things better when I move around or use signs and signals while learning",
    "facetCode": "K",
    "facetName": "Kinesthetic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 79,
    "itemId": "LRN19",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I learn best when I can touch and work with objects physically",
    "facetCode": "K",
    "facetName": "Kinesthetic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 80,
    "itemId": "LRN20",
    "section": "Learning Style (VARK) — supplementary",
    "questionText": "I find practical experiments more interesting than listening to lectures",
    "facetCode": "K",
    "facetName": "Kinesthetic",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 81,
    "itemId": "VAL01",
    "section": "Values (Schwartz)",
    "questionText": "I like trying new things, even if they are challenging",
    "facetCode": "OC",
    "facetName": "Openness to Change",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 82,
    "itemId": "VAL02",
    "section": "Values (Schwartz)",
    "questionText": "I enjoy bringing my own ideas and projects",
    "facetCode": "OC",
    "facetName": "Openness to Change",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 83,
    "itemId": "VAL03",
    "section": "Values (Schwartz)",
    "questionText": "I prefer working on tasks where I can be creative",
    "facetCode": "OC",
    "facetName": "Openness to Change",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 84,
    "itemId": "VAL04",
    "section": "Values (Schwartz)",
    "questionText": "I like to make my own decisions",
    "facetCode": "OC",
    "facetName": "Openness to Change",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 85,
    "itemId": "VAL05",
    "section": "Values (Schwartz)",
    "questionText": "I enjoy exploring new places and learning new things",
    "facetCode": "OC",
    "facetName": "Openness to Change",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 86,
    "itemId": "VAL06",
    "section": "Values (Schwartz)",
    "questionText": "I like tasks that allow me to think in different ways",
    "facetCode": "OC",
    "facetName": "Openness to Change",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 87,
    "itemId": "VAL07",
    "section": "Values (Schwartz)",
    "questionText": "I enjoy taking on new challenges that are different from what I usually do",
    "facetCode": "OC",
    "facetName": "Openness to Change",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 88,
    "itemId": "VAL08",
    "section": "Values (Schwartz)",
    "questionText": "I enjoy doing things differently",
    "facetCode": "OC",
    "facetName": "Openness to Change",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 89,
    "itemId": "VAL09",
    "section": "Values (Schwartz)",
    "questionText": "I prefer having the freedom to choose how I do my work",
    "facetCode": "OC",
    "facetName": "Openness to Change",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 90,
    "itemId": "VAL10",
    "section": "Values (Schwartz)",
    "questionText": "I try to be the best in what I do",
    "facetCode": "SE",
    "facetName": "Self-Enhancement",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 91,
    "itemId": "VAL11",
    "section": "Values (Schwartz)",
    "questionText": "I like being recognized for my achievements",
    "facetCode": "SE",
    "facetName": "Self-Enhancement",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 92,
    "itemId": "VAL12",
    "section": "Values (Schwartz)",
    "questionText": "I enjoy setting goals and working hard to achieve them",
    "facetCode": "SE",
    "facetName": "Self-Enhancement",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 93,
    "itemId": "VAL13",
    "section": "Values (Schwartz)",
    "questionText": "I want to be in a position where I can make important decisions",
    "facetCode": "SE",
    "facetName": "Self-Enhancement",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 94,
    "itemId": "VAL14",
    "section": "Values (Schwartz)",
    "questionText": "I feel proud when I accomplish something difficult",
    "facetCode": "SE",
    "facetName": "Self-Enhancement",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 95,
    "itemId": "VAL15",
    "section": "Values (Schwartz)",
    "questionText": "I like to be in charge of group projects or activities",
    "facetCode": "SE",
    "facetName": "Self-Enhancement",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 96,
    "itemId": "VAL16",
    "section": "Values (Schwartz)",
    "questionText": "I enjoy being a leader and guiding others",
    "facetCode": "SE",
    "facetName": "Self-Enhancement",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 97,
    "itemId": "VAL17",
    "section": "Values (Schwartz)",
    "questionText": "I want to be successful and have a good reputation",
    "facetCode": "SE",
    "facetName": "Self-Enhancement",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 98,
    "itemId": "VAL18",
    "section": "Values (Schwartz)",
    "questionText": "I like to show others that I am capable and skilled",
    "facetCode": "SE",
    "facetName": "Self-Enhancement",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 99,
    "itemId": "VAL19",
    "section": "Values (Schwartz)",
    "questionText": "I feel motivated when I have the chance to win or excel",
    "facetCode": "SE",
    "facetName": "Self-Enhancement",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 100,
    "itemId": "VAL20",
    "section": "Values (Schwartz)",
    "questionText": "I feel confident when I follow rules and do what is expected",
    "facetCode": "CO",
    "facetName": "Conservation",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 101,
    "itemId": "VAL21",
    "section": "Values (Schwartz)",
    "questionText": "I like to keep things in order and make sure everything is secure",
    "facetCode": "CO",
    "facetName": "Conservation",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 102,
    "itemId": "VAL22",
    "section": "Values (Schwartz)",
    "questionText": "I try to avoid doing things that might upset others",
    "facetCode": "CO",
    "facetName": "Conservation",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 103,
    "itemId": "VAL23",
    "section": "Values (Schwartz)",
    "questionText": "I feel comfortable when things stay the same and don't change too much",
    "facetCode": "CO",
    "facetName": "Conservation",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 104,
    "itemId": "VAL24",
    "section": "Values (Schwartz)",
    "questionText": "I believe it is important to follow the rules and regulations",
    "facetCode": "CO",
    "facetName": "Conservation",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 105,
    "itemId": "VAL25",
    "section": "Values (Schwartz)",
    "questionText": "I like being in environments where I know what to expect",
    "facetCode": "CO",
    "facetName": "Conservation",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 106,
    "itemId": "VAL26",
    "section": "Values (Schwartz)",
    "questionText": "I think it's important to be polite and respectful to everyone",
    "facetCode": "CO",
    "facetName": "Conservation",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 107,
    "itemId": "VAL27",
    "section": "Values (Schwartz)",
    "questionText": "I value stability and like to keep things predictable",
    "facetCode": "CO",
    "facetName": "Conservation",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 108,
    "itemId": "VAL28",
    "section": "Values (Schwartz)",
    "questionText": "I enjoy helping others when they need support",
    "facetCode": "ST",
    "facetName": "Self-Transcendence",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 109,
    "itemId": "VAL29",
    "section": "Values (Schwartz)",
    "questionText": "I try to make sure everyone is treated fairly",
    "facetCode": "ST",
    "facetName": "Self-Transcendence",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 110,
    "itemId": "VAL30",
    "section": "Values (Schwartz)",
    "questionText": "I feel happy when I can make someone's day better",
    "facetCode": "ST",
    "facetName": "Self-Transcendence",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 111,
    "itemId": "VAL31",
    "section": "Values (Schwartz)",
    "questionText": "I believe it's important to protect the environment and nature",
    "facetCode": "ST",
    "facetName": "Self-Transcendence",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 112,
    "itemId": "VAL32",
    "section": "Values (Schwartz)",
    "questionText": "I try to be kind and considerate to everyone I meet",
    "facetCode": "ST",
    "facetName": "Self-Transcendence",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 113,
    "itemId": "VAL33",
    "section": "Values (Schwartz)",
    "questionText": "I feel good when I help my friends with their problems",
    "facetCode": "ST",
    "facetName": "Self-Transcendence",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 114,
    "itemId": "VAL34",
    "section": "Values (Schwartz)",
    "questionText": "I believe it's important to support people who are being treated unfairly",
    "facetCode": "ST",
    "facetName": "Self-Transcendence",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 115,
    "itemId": "VAL35",
    "section": "Values (Schwartz)",
    "questionText": "I enjoy doing things that benefit the community or the world",
    "facetCode": "ST",
    "facetName": "Self-Transcendence",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 116,
    "itemId": "VAL36",
    "section": "Values (Schwartz)",
    "questionText": "I think it is important to understand and respect people who are different from me",
    "facetCode": "ST",
    "facetName": "Self-Transcendence",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 117,
    "itemId": "VAL37",
    "section": "Values (Schwartz)",
    "questionText": "I feel a sense of responsibility to take care of others",
    "facetCode": "ST",
    "facetName": "Self-Transcendence",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 118,
    "itemId": "GOL01",
    "section": "Goal Orientation — supplementary",
    "questionText": "I am committed to a career that requires advanced degrees, so I am willing to spend several more years in school to achieve that goal",
    "facetCode": "L",
    "facetName": "Long path (further education)",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 119,
    "itemId": "GOL02",
    "section": "Goal Orientation — supplementary",
    "questionText": "I feel that gaining practical work experience quickly is more important than pursuing a lengthy educational program",
    "facetCode": "S",
    "facetName": "Short path (fast to work)",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 120,
    "itemId": "GOL03",
    "section": "Goal Orientation — supplementary",
    "questionText": "I am open to taking student loans or seeking financial aid to fund my education for a specialized career path",
    "facetCode": "L",
    "facetName": "Long path (further education)",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 121,
    "itemId": "GOL04",
    "section": "Goal Orientation — supplementary",
    "questionText": "I would rather start working immediately and gain experience on the job, rather than spending additional years for education",
    "facetCode": "S",
    "facetName": "Short path (fast to work)",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 122,
    "itemId": "GOL05",
    "section": "Goal Orientation — supplementary",
    "questionText": "I am ready to invest time and money in further education if it means having better job opportunities in the future",
    "facetCode": "L",
    "facetName": "Long path (further education)",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 123,
    "itemId": "GOL06",
    "section": "Goal Orientation — supplementary",
    "questionText": "I am willing to opt for a part-time job or take on internships during my studies to gain experience while pursuing my long-term career goals",
    "facetCode": "L",
    "facetName": "Long path (further education)",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 124,
    "itemId": "GOL07",
    "section": "Goal Orientation — supplementary",
    "questionText": "I am interested in finding a job right after college, even if it means starting in a position that doesn't require a lot of education",
    "facetCode": "S",
    "facetName": "Short path (fast to work)",
    "responseType": "likert5",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1=Strongly disagree ... 5=Strongly agree",
    "hasImage": null,
    "countsTowardClusterMatch": "No — supplementary"
  },
  {
    "no": 125,
    "itemId": "APT01",
    "section": "Aptitude",
    "questionText": "In a class of 30 students, 20 have taken Mathematics, 15 have taken Physics, and 10 have taken both. How many students have taken neither Mathematics nor Physics?",
    "facetCode": "Log",
    "facetName": "Logical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) 5 [CORRECT]  2) 10  3) 20  4) None of the above",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 126,
    "itemId": "APT02",
    "section": "Aptitude",
    "questionText": "A man is facing north. He turns 90° clockwise, then 180° anti-clockwise, then 90° to his left side, then another 45° to his right-hand side. Which direction is he facing now?",
    "facetCode": "Log",
    "facetName": "Logical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) North East  2) South West [CORRECT]  3) East  4) West",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 127,
    "itemId": "APT03",
    "section": "Aptitude",
    "questionText": "If TRAIN is coded as WUDLQ, how will PLANE be coded?",
    "facetCode": "Log",
    "facetName": "Logical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) SMDQH  2) SMDOF  3) SODQH [CORRECT]  4) SODMH",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 128,
    "itemId": "APT04",
    "section": "Aptitude",
    "questionText": "If it was a Sunday on 11 June 2017, what was the day of the week on 26 November 2017?",
    "facetCode": "Log",
    "facetName": "Logical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Monday  2) Tuesday  3) Sunday [CORRECT]  4) Friday",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 129,
    "itemId": "APT05",
    "section": "Aptitude",
    "questionText": "Kabir's father is Raj. Raj's brother is Sahil. Sahil's son is Amir. How is Kabir related to Amir?",
    "facetCode": "Log",
    "facetName": "Logical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Cousin [CORRECT]  2) Brother  3) Uncle  4) Nephew",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 130,
    "itemId": "APT06",
    "section": "Aptitude",
    "questionText": "Series: 7 O * E B # I 9 P U % K Z $ A 0 — How many vowels are immediately preceded by a symbol?",
    "facetCode": "Log",
    "facetName": "Logical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) One  2) Two  3) Three [CORRECT]  4) None",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 131,
    "itemId": "APT07",
    "section": "Aptitude",
    "questionText": "Complete: 'Youth is the time ___ the seeds of character are sown.'",
    "facetCode": "Voc",
    "facetName": "Vocabulary",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) When [CORRECT]  2) Where  3) Which  4) That",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 132,
    "itemId": "APT08",
    "section": "Aptitude",
    "questionText": "'I told him that he was not working hard.' — direct speech form:",
    "facetCode": "Voc",
    "facetName": "Vocabulary",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) I told him, \"You were not working hard.\"  2) I said to him, \"He is not working hard.\"  3) I said, \"You are not working hard.\"  4) I said to him, \"You are not working hard.\" [CORRECT]",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 133,
    "itemId": "APT09",
    "section": "Aptitude",
    "questionText": "[Internet passage] Which option best describes the main idea?",
    "facetCode": "Voc",
    "facetName": "Vocabulary",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) The Internet has made personal privacy stronger than before.  2) The Internet provides rapid access to information but poses challenges like privacy concerns. [CORRECT]  3) The Internet spreads misinformation intentionally.  4) Communication has remained unchanged despite technological advancements.",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 134,
    "itemId": "APT10",
    "section": "Aptitude",
    "questionText": "Identify the grammatically correct sentence:",
    "facetCode": "Voc",
    "facetName": "Vocabulary",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Each of the students have a book.  2) Neither of the answers were correct.  3) The team has decided to postpone its meeting. [CORRECT]  4) He don't know the answer to the question.",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 135,
    "itemId": "APT11",
    "section": "Aptitude",
    "questionText": "Find the incorrect part: 'Barely had he arrived to the office when the phone rang.'",
    "facetCode": "Voc",
    "facetName": "Vocabulary",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Barely  2) had he  3) arrived to the office [CORRECT]  4) when the phone rang",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 136,
    "itemId": "APT12",
    "section": "Aptitude",
    "questionText": "Word most similar in meaning to 'Ubiquitous':",
    "facetCode": "Voc",
    "facetName": "Vocabulary",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Rare  2) Widespread [CORRECT]  3) Unique  4) Specific",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 137,
    "itemId": "APT13",
    "section": "Aptitude",
    "questionText": "Profit is 220% of cost. Cost rises 10%, selling price constant. Profit is approximately what % of selling price?",
    "facetCode": "Num",
    "facetName": "Numerical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) 66 [CORRECT]  2) 54  3) 60  4) 76",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 138,
    "itemId": "APT14",
    "section": "Aptitude",
    "questionText": "Binay (17 km/hr) and Surjay (19 km/hr) travel X to Y, 72 km apart. Surjay reaches Y, returns, meets Binay at Z. Distance Z to Y (km)?",
    "facetCode": "Num",
    "facetName": "Numerical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) 4 [CORRECT]  2) 6  3) 7  4) 5",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 139,
    "itemId": "APT15",
    "section": "Aptitude",
    "questionText": "In what time does money become 4.2 times itself at 16% p.a. simple interest?",
    "facetCode": "Num",
    "facetName": "Numerical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) 15 years  2) 20 years [CORRECT]  3) 30 years  4) None of the above",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 140,
    "itemId": "APT16",
    "section": "Aptitude",
    "questionText": "A and B complete work in 21 and 28 days; contract is ₹49,000. B's share?",
    "facetCode": "Num",
    "facetName": "Numerical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) ₹28,000  2) ₹24,000  3) ₹23,000  4) ₹21,000 [CORRECT]",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 141,
    "itemId": "APT17",
    "section": "Aptitude",
    "questionText": "Sum of the first 50 natural numbers:",
    "facetCode": "Num",
    "facetName": "Numerical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) 1175  2) 1275 [CORRECT]  3) 1325  4) 1375",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 142,
    "itemId": "APT18",
    "section": "Aptitude",
    "questionText": "If p(x) = x² − 5x + 6, find p(2).",
    "facetCode": "Num",
    "facetName": "Numerical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) 0 [CORRECT]  2) 2  3) 4  4) -1",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 143,
    "itemId": "APT19",
    "section": "Aptitude",
    "questionText": "Product of two numbers is 120, sum is 26. The numbers are:",
    "facetCode": "Num",
    "facetName": "Numerical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) 12 and 10  2) 15 and 11  3) 20 and 6 [CORRECT]  4) 24 and 2",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 144,
    "itemId": "APT20",
    "section": "Aptitude",
    "questionText": "If bar X moves to the left, which way will bar Y move?",
    "facetCode": "Mech",
    "facetName": "Mechanical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Left  2) Right [CORRECT]  3) Will not move  4) Data is not sufficient",
    "hasImage": "Yes",
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 145,
    "itemId": "APT21",
    "section": "Aptitude",
    "questionText": "What type of initial energy is converted to kinetic energy when a car accelerates?",
    "facetCode": "Mech",
    "facetName": "Mechanical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Chemical [CORRECT]  2) Kinetic  3) Thermal  4) Electrical",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 146,
    "itemId": "APT22",
    "section": "Aptitude",
    "questionText": "Single fixed ideal pulley lifting 150 kg (g = 9.8 m/s²). Force needed?",
    "facetCode": "Mech",
    "facetName": "Mechanical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) 150 N  2) 1000 N  3) 1500 N  4) 1470 N [CORRECT]",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 147,
    "itemId": "APT23",
    "section": "Aptitude",
    "questionText": "What would be the current flowing through point X if another identical power source were to be added in parallel to the circuit?",
    "facetCode": "Mech",
    "facetName": "Mechanical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Twice as strong  2) Half as strong  3) There is no difference [CORRECT]  4) Not enough data",
    "hasImage": "Yes",
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 148,
    "itemId": "APT24",
    "section": "Aptitude",
    "questionText": "Load of 100 N lifted with 50 N force in a pulley system. Mechanical advantage?",
    "facetCode": "Mech",
    "facetName": "Mechanical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) 1  2) 2 [CORRECT]  3) 4  4) 0.5",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 149,
    "itemId": "APT25",
    "section": "Aptitude",
    "questionText": "Seesaw: 40 kg boy sits 2 m from fulcrum. How far should a 30 kg boy sit to balance (m)?",
    "facetCode": "Mech",
    "facetName": "Mechanical",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) 2.67 [CORRECT]  2) 3.55  3) 1.53  4) 2.00",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 150,
    "itemId": "APT26",
    "section": "Aptitude",
    "questionText": "Arrange: widespread / has / in / modern / technology / society / a / impact",
    "facetCode": "Verb",
    "facetName": "Verbal",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Modern society has a widespread impact in technology.  2) Technology has a widespread impact in modern society. [CORRECT]  3) Modern technology in society has a widespread impact.  4) Society has a widespread impact in modern technology.",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 151,
    "itemId": "APT27",
    "section": "Aptitude",
    "questionText": "[Penicillin paragraph jumble] Correct sequence of P, Q, R, S after S1:",
    "facetCode": "Verb",
    "facetName": "Verbal",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) RQPS  2) RQSP  3) RSQP [CORRECT]  4) QSPR",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 152,
    "itemId": "APT28",
    "section": "Aptitude",
    "questionText": "Sentence using 'apprehensive' correctly:",
    "facetCode": "Verb",
    "facetName": "Verbal",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) She felt apprehensive before her first day at the new school. [CORRECT]  2) The apprehensive sun shone brightly over the clear blue sky.  3) He cooked the meal with apprehensive ingredients from the garden.  4) The car drove apprehensive down the road at high speed.",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 153,
    "itemId": "APT29",
    "section": "Aptitude",
    "questionText": "[Planning statement] Which conclusion can be drawn?",
    "facetCode": "Verb",
    "facetName": "Verbal",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Students who plan never face any difficulties in life.  2) Planning is essential for academic success. [CORRECT]  3) Only successful students plan their studies.  4) Students who plan their studies never face difficulties.",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 154,
    "itemId": "APT30",
    "section": "Aptitude",
    "questionText": "Wisdom is to wise as strength is to ___.",
    "facetCode": "Verb",
    "facetName": "Verbal",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Strong [CORRECT]  2) Strengthen  3) Weak  4) Strife",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 155,
    "itemId": "APT31",
    "section": "Aptitude",
    "questionText": "[Cats/mammals/dogs syllogism] Which conclusion follows logically?",
    "facetCode": "Verb",
    "facetName": "Verbal",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) All cats are dogs.  2) Some animals are not dogs. [CORRECT]  3) All mammals are cats.  4) Some dogs are not mammals.",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 156,
    "itemId": "APT32",
    "section": "Aptitude",
    "questionText": "Cryptic is to Mysterious as Transparent is to ___.",
    "facetCode": "Verb",
    "facetName": "Verbal",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Opaque  2) Clear [CORRECT]  3) Foggy  4) Hidden",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 157,
    "itemId": "APT33",
    "section": "Aptitude",
    "questionText": "Minimum number of cuts to divide a round cake into 8 equal pieces:",
    "facetCode": "Spat",
    "facetName": "Spatial",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) 2  2) 3 [CORRECT]  3) 4  4) 5",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 158,
    "itemId": "APT34",
    "section": "Aptitude",
    "questionText": "Which figure is identical to the first figure given below?",
    "facetCode": "Spat",
    "facetName": "Spatial",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) A  2) B  3) C  4) D [CORRECT]",
    "hasImage": "Yes",
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 159,
    "itemId": "APT35",
    "section": "Aptitude",
    "questionText": "If the picture below is rotated, which one of the following options is the result of the rotation?",
    "facetCode": "Spat",
    "facetName": "Spatial",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Figure 1  2) Figure 2  3) Figure 3  4) Figure 4 [CORRECT]",
    "hasImage": "Yes",
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 160,
    "itemId": "APT36",
    "section": "Aptitude",
    "questionText": "These are different views of the same cube. What colour is the bottom of the middle cube?",
    "facetCode": "Spat",
    "facetName": "Spatial",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Blue  2) Red  3) Orange  4) Green [CORRECT]",
    "hasImage": "Yes",
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 161,
    "itemId": "APT37",
    "section": "Aptitude",
    "questionText": "Find the missing part to complete the image.",
    "facetCode": "Spat",
    "facetName": "Spatial",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) Option 1 [CORRECT]  2) Option 2  3) Option 3  4) Option 4  5) Option 5",
    "hasImage": "Yes",
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 162,
    "itemId": "APT38",
    "section": "Aptitude",
    "questionText": "Cube painted on all sides, cut into 64 equal cubes. How many have exactly one painted face?",
    "facetCode": "Spat",
    "facetName": "Spatial",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) 24 [CORRECT]  2) 26  3) 22  4) 20",
    "hasImage": null,
    "countsTowardClusterMatch": "Yes"
  },
  {
    "no": 163,
    "itemId": "APT39",
    "section": "Aptitude",
    "questionText": "Which figure completes the statement?",
    "facetCode": "Spat",
    "facetName": "Spatial",
    "responseType": "mcq4",
    "reverseKeyed": "No",
    "optionsAnswerKey": "1) A  2) B  3) C  4) D [CORRECT]",
    "hasImage": "Yes",
    "countsTowardClusterMatch": "Yes"
  }
]
